openapi: 3.0.0
info:
  title: UasWebSer
  version: 1.0.0
servers:
  - url: http://localhost:2000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /regis:
    post:
      tags:
        - default
      summary: UserRegistration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rania
                password: thv301295
                name: ayu
                email: ayuniiraniaa@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: UserLogin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: rania
                password: thv301295
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /products:
    get:
      tags:
        - default
      summary: GetProduct
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostProduct
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: baju
                description: baru
                price: 500000
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /products/{id}:
    put:
      tags:
        - default
      summary: PutProduct
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the product to update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: tas
                description: baru
                price: 200000
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteProduct
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the product to delete
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders:
    get:
      tags:
        - default
      summary: GetOrder
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: PostOrder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 2
                product_id: 2
                order_status: pending
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /orders/{id}:
    put:
      tags:
        - default
      summary: PutOrder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the order to update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 2
                product_id: 2
                order_status: success
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteOrder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the order to delete
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
